### ISSUE TITLE
Implementar la función de carga de datos a SQL

### ISSUE THREAD

**Issue by AylinSenju** [AylinSenju/ProyectoFinal#7]
Como usuario, quiero cargar los datos transformados en la base de datos para almacenarlos de forma estructurada.

**CRITERIOS DE ACEPTACIÓN**
- [x] Script que inserte los datos a SQL.
- [x] Verificación de los datos se carguen correctamente y sin duplicados.

**Comment by Javierprec** [comment]
Carga de datos exitoso
